export type ToolProfile = "core" | "research" | "browser" | "native-search" | "external-api" | "local-service"

export const TOOL_PROFILES: Record<ToolProfile, readonly string[]> = {
  core: [
    "lsp_goto_definition",
    "lsp_find_references",
    "lsp_symbols",
    "lsp_diagnostics",
    "lsp_prepare_rename",
    "lsp_rename",
    "grep",
    "glob",
    "multiedit",
    "session_list",
    "session_read",
    "session_search",
    "session_info",
    "system_notify",
  ],
  research: [
    "exa_websearch",
    "exa_codesearch",
    "context7_resolve_library_id",
    "context7_query_docs",
    "grep_app_searchGitHub",
    "webfetch",
    "zread_search",
    "zread_file",
    "zread_structure",
  ],
  browser: [
    "browser_open",
    "browser_snapshot",
    "browser_screenshot",
    "browser_click",
    "browser_fill",
    "browser_close",
    "browser_back",
    "browser_forward",
    "browser_reload",
    "browser_get_url",
    "browser_get_title",
    "browser_type",
    "browser_press",
    "browser_hover",
    "browser_scroll",
    "browser_select",
    "browser_eval",
    "browser_wait",
  ],
  "native-search": ["ast_grep_search", "ast_grep_replace"],
  "external-api": [
    "runwareGenerate",
    "runwareRemoveBg",
    "runwareUpscale",
    "runwareModelSearch",
    "runwareImg2Img",
    "runwareVideoGenerate",
    "runwareVideoFromImage",
    "civitai_search",
    "civitai_get",
    "civitai_tags",
    "unified_model_search",
    "ripple_collections",
    "ripple_search",
    "ripple_get",
    "ripple_create",
    "ripple_tags",
    "ripple_tag_add",
    "ripple_tag_remove",
    "ripple_bulk_create",
    "ripple_bulk_update",
    "ripple_delete",
    "ripple_bulk_delete",
    "ripple_suggest",
  ],
  "local-service": [
    "syncthing_status",
    "syncthing_folders",
    "syncthing_folder_add",
    "syncthing_folder_remove",
    "syncthing_folder_pause",
    "syncthing_folder_rescan",
    "syncthing_devices",
    "syncthing_device_add",
    "syncthing_device_remove",
    "syncthing_share",
    "syncthing_unshare",
    "syncthing_ignores_get",
    "syncthing_ignores_set",
    "syncthing_versioning",
    "syncthing_connections",
    "ticket_ready",
    "ticket_list",
    "ticket_show",
    "ticket_create",
    "ticket_start",
    "ticket_close",
    "ticket_dep",
    "ticket_undep",
    "ticket_blocked",
  ],
}

export const TOOL_TO_PROFILE: Record<string, ToolProfile> = Object.fromEntries(
  (Object.entries(TOOL_PROFILES) as [ToolProfile, readonly string[]][]).flatMap(([profile, tools]) =>
    tools.map((toolName) => [toolName, profile] as const),
  ),
)

export function getToolProfile(toolName: string): ToolProfile | undefined {
  return TOOL_TO_PROFILE[toolName]
}

export function getToolsForProfile(profile: ToolProfile): string[] {
  return [...TOOL_PROFILES[profile]]
}
